export const CHARACTER_CONFIG = {
  Warrior: {
    spriteKey: 'warrior',
    animations: {
      idle: { key: 'warrior_idle_anim', sheet: 'warrior_idle', frameRate: 10, repeat: -1 },
      run: { key: 'warrior_run_anim', sheet: 'warrior_run', frameRate: 12, repeat: -1, frames: { start: 0, end: 5 } },
      jump: { key: 'warrior_jump_anim', sheet: 'warrior_jump', frameRate: 10, repeat: 0, frames: { start: 0, end: 5 } },
      fall: { key: 'warrior_fall_anim', sheet: 'warrior_fall', frameRate: 10, repeat: 0, frames: { start: 0, end: 5 } },
      attack1: { key: 'warrior_attack_1', sheet: 'warrior_attack1', frameRate: 12, repeat: 0 },
      attack2: { key: 'warrior_attack_2', sheet: 'warrior_attack2', frameRate: 12, repeat: 0 },
      attack3: { key: 'warrior_attack_3', sheet: 'warrior_attack3', frameRate: 10, repeat: 0 },
      takeHit: { key: 'warrior_take_hit_anim', sheet: 'warrior_takeHit', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
      death: { key: 'warrior_death_anim', sheet: 'warrior_death', frameRate: 10, repeat: 0, frames: { start: 0, end: 8 } },
    },
    sprites: {
      idle: { path: 'assets/sprites/warrior/Idle.png', frameWidth: 135, frameHeight: 135 },
      run: { path: 'assets/sprites/warrior/Run.png', frameWidth: 135, frameHeight: 135 },
      jump: { path: 'assets/sprites/warrior/Jump.png', frameWidth: 135, frameHeight: 135 },
      fall: { path: 'assets/sprites/warrior/Fall.png', frameWidth: 135, frameHeight: 135 },
      attack1: { path: 'assets/sprites/warrior/Attack1.png', frameWidth: 135, frameHeight: 135 },
      attack2: { path: 'assets/sprites/warrior/Attack2.png', frameWidth: 135, frameHeight: 135 },
      attack3: { path: 'assets/sprites/warrior/Attack3.png', frameWidth: 135, frameHeight: 135 },
      takeHit: { path: 'assets/sprites/warrior/Take_Hit.png', frameWidth: 135, frameHeight: 135 },
      death: { path: 'assets/sprites/warrior/Death.png', frameWidth: 135, frameHeight: 135 },
    },
    physics: {
      bodySize: { width: 15, height: 38 },
      bodyOffset: { x: 60, y: 47 },
      drag: 200,
      maxVelocity: { x: 250, y: 800 },
      moveSpeed: 210,
      jumpVelocity: -500,
    },
    combat: {
      damage: 50,
      attackRate: 900,
      attacks: ['warrior_attack_1', 'warrior_attack_2', 'warrior_attack_3'],
    },
    scale: 1.5,
  },

  Mage: {
    spriteKey: 'mage',
    animations: {
      idle: { key: 'mage_idle_anim', sheet: 'mage_idle', frameRate: 10, repeat: -1 },
      run: { key: 'mage_run_anim', sheet: 'mage_run', frameRate: 12, repeat: -1 },
      jump: { key: 'mage_jump_anim', sheet: 'mage_jump', frameRate: 10, repeat: 0 },
      fall: { key: 'mage_fall_anim', sheet: 'mage_fall', frameRate: 10, repeat: 0 },
      attack1: { key: 'mage_attack_1', sheet: 'mage_attack1', frameRate: 12, repeat: 0 },
      attack2: { key: 'mage_attack_2', sheet: 'mage_attack2', frameRate: 12, repeat: 0 },
      takeHit: { key: 'mage_take_hit_anim', sheet: 'mage_takeHit', frameRate: 10, repeat: 0 },
      death: { key: 'mage_death_anim', sheet: 'mage_death', frameRate: 10, repeat: 0 },
    },
    sprites: {
      idle: { path: 'assets/sprites/mage/Idle.png', frameWidth: 231, frameHeight: 190 },
      run: { path: 'assets/sprites/mage/Run.png', frameWidth: 231, frameHeight: 190 },
      jump: { path: 'assets/sprites/mage/Jump.png', frameWidth: 231, frameHeight: 190 },
      fall: { path: 'assets/sprites/mage/Fall.png', frameWidth: 231, frameHeight: 190 },
      attack1: { path: 'assets/sprites/mage/Attack1.png', frameWidth: 231, frameHeight: 190 },
      attack2: { path: 'assets/sprites/mage/Attack2.png', frameWidth: 231, frameHeight: 190 },
      takeHit: { path: 'assets/sprites/mage/Take_Hit.png', frameWidth: 231, frameHeight: 190 },
      death: { path: 'assets/sprites/mage/Death.png', frameWidth: 231, frameHeight: 190 },
    },
    physics: {
      bodySize: { width: 40, height: 77 },
      bodyOffset: { x: 95.5, y: 63 },
      drag: 200,
      maxVelocity: { x: 250, y: 800 },
      moveSpeed: 210,
      jumpVelocity: -500,
    },
    combat: {
      damage: 70,
      attackRate: 1200,
      attacks: ['mage_attack_1', 'mage_attack_2'],
    },
    scale: 0.78,
  },

  Archer: {
    spriteKey: 'archer',
    animations: {
      idle: { key: 'archer_idle_anim', sheet: 'archer_idle', frameRate: 10, repeat: -1, frames: { start: 0, end: 9 } },
      run: { key: 'archer_run_anim', sheet: 'archer_run', frameRate: 12, repeat: -1, frames: { start: 0, end: 7 } },
      jump: { key: 'archer_jump_anim', sheet: 'archer_jump', frameRate: 10, repeat: 0, frames: { start: 0, end: 1 } },
      fall: { key: 'archer_fall_anim', sheet: 'archer_fall', frameRate: 10, repeat: 0, frames: { start: 0, end: 1 } },
      attack1: { key: 'archer_attack_1', sheet: 'archer_attack', frameRate: 12, repeat: 0, frames: { start: 0, end: 5 } },
      arrowMove: { key: 'archer_arrow_move_anim', sheet: 'archer_arrowMove', frameRate: 18, repeat: -1 },
      takeHit: { key: 'archer_take_hit_anim', sheet: 'archer_takeHit', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
      death: { key: 'archer_death_anim', sheet: 'archer_death', frameRate: 10, repeat: 0, frames: { start: 0, end: 9 } },
    },
    sprites: {
      idle: { path: 'assets/sprites/archer/Idle.png', frameWidth: 100, frameHeight: 100 },
      run: { path: 'assets/sprites/archer/Run.png', frameWidth: 100, frameHeight: 100 },
      jump: { path: 'assets/sprites/archer/Jump.png', frameWidth: 100, frameHeight: 100 },
      fall: { path: 'assets/sprites/archer/Fall.png', frameWidth: 100, frameHeight: 100 },
      attack: { path: 'assets/sprites/archer/Attack.png', frameWidth: 100, frameHeight: 100 },
      arrowMove: { path: 'assets/sprites/archer/Arrow_Move.png', frameWidth: 24, frameHeight: 5 },
      takeHit: { path: 'assets/sprites/archer/Take_Hit.png', frameWidth: 100, frameHeight: 100 },
      death: { path: 'assets/sprites/archer/Death.png', frameWidth: 100, frameHeight: 100 },
    },
    physics: {
      bodySize: { width: 15, height: 35 },
      bodyOffset: { x: 44, y: 32 },
      drag: 200,
      maxVelocity: { x: 250, y: 800 },
      moveSpeed: 210,
      jumpVelocity: -500,
    },
    combat: {
      damage: 40,
      attackRate: 600,
      attacks: ['archer_attack_1'],
    },
    scale: 1.6,
  },

  Witch: {
    spriteKey: 'witch',
    animations: {
      idle: { key: 'witch_idle_anim', sheet: 'witch_idle', frameRate: 10, repeat: -1, frames: { start: 0, end: 9 } },
      run: { key: 'witch_run_anim', sheet: 'witch_run', frameRate: 12, repeat: -1, frames: { start: 0, end: 7 } },
      jump: { key: 'witch_jump_anim', sheet: 'witch_jump', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
      fall: { key: 'witch_fall_anim', sheet: 'witch_fall', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
      attack1: { key: 'witch_attack_1', sheet: 'witch_attack', frameRate: 12, repeat: 0, frames: { start: 0, end: 12 } },
      projectileMove: { key: 'witch_projectile_move_anim', sheet: 'witch_moving', frameRate: 18, repeat: -1, frames: { start: 0, end: 3 } },
      projectileExplode: { key: 'witch_projectile_explode_anim', sheet: 'witch_explode', frameRate: 20, repeat: 0, frames: { start: 0, end: 6 } },
      takeHit: { key: 'witch_take_hit_anim', sheet: 'witch_takeHit', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
      death: { key: 'witch_death_anim', sheet: 'witch_death', frameRate: 10, repeat: 0, frames: { start: 0, end: 17 } },
    },
    sprites: {
      idle: { path: 'assets/sprites/witch/Idle.png', frameWidth: 140, frameHeight: 140 },
      run: { path: 'assets/sprites/witch/Run.png', frameWidth: 140, frameHeight: 140 },
      jump: { path: 'assets/sprites/witch/Jump.png', frameWidth: 140, frameHeight: 140 },
      fall: { path: 'assets/sprites/witch/Fall.png', frameWidth: 140, frameHeight: 140 },
      attack: { path: 'assets/sprites/witch/Attack.png', frameWidth: 140, frameHeight: 140 },
      moving: { path: 'assets/sprites/witch/Moving.png', frameWidth: 50, frameHeight: 50 },
      explode: { path: 'assets/sprites/witch/Explode.png', frameWidth: 50, frameHeight: 50 },
      takeHit: { path: 'assets/sprites/witch/Take_Hit.png', frameWidth: 140, frameHeight: 140 },
      death: { path: 'assets/sprites/witch/Death.png', frameWidth: 140, frameHeight: 140 },
    },
    physics: {
      bodySize: { width: 24, height: 53 },
      bodyOffset: { x: 58, y: 44 },
      drag: 200,
      maxVelocity: { x: 250, y: 800 },
      moveSpeed: 210,
      jumpVelocity: -500,
    },
    combat: {
      damage: 30,
      attackRate: 1000,
      attacks: ['witch_attack_1'],
    },
    scale: 1.1,
  },
};

export const BOSS_CONFIG = {
  spriteKey: 'boss',
  animations: {
    idle: { key: 'boss_idle_anim', sheet: 'boss_idle', frameRate: 8, repeat: -1, frames: { start: 0, end: 7 } },
    run: { key: 'boss_run_anim', sheet: 'boss_run', frameRate: 10, repeat: -1, frames: { start: 0, end: 7 } },
    jump: { key: 'boss_jump_anim', sheet: 'boss_jump', frameRate: 10, repeat: 0, frames: { start: 0, end: 5 } },
    fall: { key: 'boss_fall_anim', sheet: 'boss_fall', frameRate: 10, repeat: 0, frames: { start: 0, end: 5 } },
    attack1: { key: 'boss_attack_1_anim', sheet: 'boss_attack_1', frameRate: 12, repeat: 0, frames: { start: 0, end: 5 } },
    attack2: { key: 'boss_attack_2_anim', sheet: 'boss_attack_2', frameRate: 12, repeat: 0, frames: { start: 0, end: 5 } },
    takeHit: { key: 'boss_take_hit_anim', sheet: 'boss_take_hit', frameRate: 10, repeat: 0, frames: { start: 0, end: 2 } },
    death: { key: 'boss_death_anim', sheet: 'boss_death', frameRate: 8, repeat: 0, frames: { start: 0, end: 5 } },
  },
  sprites: {
    idle: { path: 'assets/sprites/war_boss/Idle.png', frameWidth: 200, frameHeight: 200 },
    run: { path: 'assets/sprites/war_boss/Run.png', frameWidth: 200, frameHeight: 200 },
    jump: { path: 'assets/sprites/war_boss/Jump.png', frameWidth: 200, frameHeight: 200 },
    fall: { path: 'assets/sprites/war_boss/Fall.png', frameWidth: 200, frameHeight: 200 },
    attack1: { path: 'assets/sprites/war_boss/Attack1.png', frameWidth: 200, frameHeight: 200 },
    attack2: { path: 'assets/sprites/war_boss/Attack2.png', frameWidth: 200, frameHeight: 200 },
    takeHit: { path: 'assets/sprites/war_boss/Take_Hit.png', frameWidth: 200, frameHeight: 200 },
    death: { path: 'assets/sprites/war_boss/Death.png', frameWidth: 200, frameHeight: 200 },
  },
  physics: {
    bodySize: { width: 20, height: 50 },
    bodyOffset: { x: 90, y: 72 },
  },
  combat: {
    attacks: [
      { key: 'boss_attack_1_anim', damage: 40 },
      { key: 'boss_attack_2_anim', damage: 60 },
    ],
  },
  scale: 2.5,
};




